name: dsh
volumes:
  dsh_config:

services:
  deepseek-harness:
    container_name: dsh-deepseek-harness
    build:
      context: ./deepseek-harness
      dockerfile: ../dsh.dockerfile
    ports:
      - "127.0.0.1:3080:3080"
    restart: no
    security_opt:
      - no-new-privileges:true
    volumes:
      - dsh_config:/root/.dsh
      - ${HOME}/containers/dsh/:/root/containers/dsh/
