name: dsh

services:
  searxng:
    image: searxng/searxng:latest
    container_name: dsh-searxng
    ports:
      - "127.0.0.1:3081:8080" # Also allow host access
    environment:
      - FORCE_OWNERSHIP=false
    restart: unless-stopped
    volumes:
      - ./config/searxng:/etc/searxng # Uses existing config. Sets .json format, needed by dsh plugin 'dsh-searxng'

  deepseek-harness:
    container_name: dsh-deepseek-harness
    build:
      context: .
      dockerfile: dsh.dockerfile
    ports:
      - "127.0.0.1:3080:3080"
    depends_on:
      - searxng
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080
      - DSH_WEB_SEARCH_PROVIDER=searxng
      - PUID=${PUID:-1000} # TODO: Pass by executing user UID, not always 1000
      - PGID=${PGID:-1000} # TODO: Pass by executing user GID, not always 1000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes: # KEEP THE FIRST LINE. The rest `dsh volume` adds/removes automatically
      - ./config/dsh:/home/node/.dsh
      - ${HOME}/code/school/07-webdev2/memory-mall/backend/:/home/node/code/school/07-webdev2/memory-mall/backend/
      - ${HOME}/code/school/07-webdev2/memory-mall/compose.yml:/home/node/code/school/07-webdev2/memory-mall/compose.yml
      - ${HOME}/code/school/07-webdev2/memory-mall/docs/:/home/node/code/school/07-webdev2/memory-mall/docs/
      - ${HOME}/code/school/07-webdev2/memory-mall/.env.example:/home/node/code/school/07-webdev2/memory-mall/.env.example
      - ${HOME}/code/school/07-webdev2/memory-mall/.env.production:/home/node/code/school/07-webdev2/memory-mall/.env.production
      - ${HOME}/code/school/07-webdev2/memory-mall/.env.test:/home/node/code/school/07-webdev2/memory-mall/.env.test
      - ${HOME}/code/school/07-webdev2/memory-mall/express.dockerfile:/home/node/code/school/07-webdev2/memory-mall/express.dockerfile
      - ${HOME}/code/school/07-webdev2/memory-mall/frontend/:/home/node/code/school/07-webdev2/memory-mall/frontend/
      - ${HOME}/code/school/07-webdev2/memory-mall/.git/:/home/node/code/school/07-webdev2/memory-mall/.git/
      - ${HOME}/code/school/07-webdev2/memory-mall/.gitignore:/home/node/code/school/07-webdev2/memory-mall/.gitignore
      - ${HOME}/code/school/07-webdev2/memory-mall/.idea/:/home/node/code/school/07-webdev2/memory-mall/.idea/
      - ${HOME}/code/school/07-webdev2/memory-mall/nuxt.dockerfile:/home/node/code/school/07-webdev2/memory-mall/nuxt.dockerfile
      - ${HOME}/code/school/07-webdev2/memory-mall/.prettierrc:/home/node/code/school/07-webdev2/memory-mall/.prettierrc
      - ${HOME}/code/school/07-webdev2/memory-mall/README.md:/home/node/code/school/07-webdev2/memory-mall/README.md
      - ${HOME}/code/school/07-webdev2/memory-mall/shared/:/home/node/code/school/07-webdev2/memory-mall/shared/
      - ${HOME}/code/school/07-webdev2/memory-mall/.agents/:/home/node/code/school/07-webdev2/memory-mall/.agents/
      - ${HOME}/containers/dsh/:/home/node/containers/dsh/
      - ${HOME}/code/school/07-webdev2/memory-mall/node_modules/:/home/node/code/school/07-webdev2/memory-mall/node_modules/
      - ${HOME}/code/school/07-webdev2/memory-mall/package.json:/home/node/code/school/07-webdev2/memory-mall/package.json
      - ${HOME}/code/school/07-webdev2/memory-mall/package-lock.json:/home/node/code/school/07-webdev2/memory-mall/package-lock.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/app/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/app/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/compose.yaml:/home/node/code/cobra-systems/todo-app/todo-app-frontend/compose.yaml
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/docs/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/docs/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/.env.example:/home/node/code/cobra-systems/todo-app/todo-app-frontend/.env.example
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/.git/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/.git/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/.github/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/.github/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/.gitignore:/home/node/code/cobra-systems/todo-app/todo-app-frontend/.gitignore
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/node_modules/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/node_modules/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/.nuxt/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/.nuxt/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/nuxt.config.ts:/home/node/code/cobra-systems/todo-app/todo-app-frontend/nuxt.config.ts
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/nuxt.dockerfile:/home/node/code/cobra-systems/todo-app/todo-app-frontend/nuxt.dockerfile
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/package.json:/home/node/code/cobra-systems/todo-app/todo-app-frontend/package.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/pnpm-lock.yaml:/home/node/code/cobra-systems/todo-app/todo-app-frontend/pnpm-lock.yaml
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/public/:/home/node/code/cobra-systems/todo-app/todo-app-frontend/public/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/README.md:/home/node/code/cobra-systems/todo-app/todo-app-frontend/README.md
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/tsconfig.json:/home/node/code/cobra-systems/todo-app/todo-app-frontend/tsconfig.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/app/:/home/node/code/cobra-systems/todo-app/todo-app-backend/app/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/artisan:/home/node/code/cobra-systems/todo-app/todo-app-backend/artisan
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/bootstrap/:/home/node/code/cobra-systems/todo-app/todo-app-backend/bootstrap/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/chisel-paths.php:/home/node/code/cobra-systems/todo-app/todo-app-backend/chisel-paths.php
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/chisel.php:/home/node/code/cobra-systems/todo-app/todo-app-backend/chisel.php
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/components.json:/home/node/code/cobra-systems/todo-app/todo-app-backend/components.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/composer.json:/home/node/code/cobra-systems/todo-app/todo-app-backend/composer.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/config/:/home/node/code/cobra-systems/todo-app/todo-app-backend/config/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/database/:/home/node/code/cobra-systems/todo-app/todo-app-backend/database/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.editorconfig:/home/node/code/cobra-systems/todo-app/todo-app-backend/.editorconfig
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.env.example:/home/node/code/cobra-systems/todo-app/todo-app-backend/.env.example
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.git/:/home/node/code/cobra-systems/todo-app/todo-app-backend/.git/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.gitattributes:/home/node/code/cobra-systems/todo-app/todo-app-backend/.gitattributes
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.github/:/home/node/code/cobra-systems/todo-app/todo-app-backend/.github/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.gitignore:/home/node/code/cobra-systems/todo-app/todo-app-backend/.gitignore
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/.npmrc:/home/node/code/cobra-systems/todo-app/todo-app-backend/.npmrc
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/package.json:/home/node/code/cobra-systems/todo-app/todo-app-backend/package.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/phpstan.neon:/home/node/code/cobra-systems/todo-app/todo-app-backend/phpstan.neon
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/phpunit.xml:/home/node/code/cobra-systems/todo-app/todo-app-backend/phpunit.xml
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/pint.json:/home/node/code/cobra-systems/todo-app/todo-app-backend/pint.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/pnpm-workspace.yaml:/home/node/code/cobra-systems/todo-app/todo-app-backend/pnpm-workspace.yaml
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/public/:/home/node/code/cobra-systems/todo-app/todo-app-backend/public/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/resources/:/home/node/code/cobra-systems/todo-app/todo-app-backend/resources/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/routes/:/home/node/code/cobra-systems/todo-app/todo-app-backend/routes/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/storage/:/home/node/code/cobra-systems/todo-app/todo-app-backend/storage/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/tests/:/home/node/code/cobra-systems/todo-app/todo-app-backend/tests/
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/tsconfig.json:/home/node/code/cobra-systems/todo-app/todo-app-backend/tsconfig.json
      - ${HOME}/code/cobra-systems/todo-app/todo-app-backend/vite.config.ts:/home/node/code/cobra-systems/todo-app/todo-app-backend/vite.config.ts
      - ${HOME}/code/cobra-systems/todo-app/todo-app-frontend/pnpm-workspace.yaml:/home/node/code/cobra-systems/todo-app/todo-app-frontend/pnpm-workspace.yaml
